import { TwitterList } from '@/types/custom';

export const twitterList: TwitterList[] = [
  {
    no: 1,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make brilliant fried fish`,
    tweetImages: [
      '/images/twitter01.png',
      '/images/twitter02.png',
      '/images/twitter03.png',
      '/images/twitter04.png',
    ],
  },
  {
    no: 2,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make wonderful fish saute`,
    tweetImages: [
      '/images/twitter01.png',
      '/images/twitter02.png',
      '/images/twitter03.png',
      '/images/twitter04.png',
    ],
  },
  {
    no: 3,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make amazing fish pasta`,
    tweetImages: [
      '/images/twitter01.png',
      '/images/twitter02.png',
      '/images/twitter03.png',
      '/images/twitter04.png',
    ],
  },
  {
    no: 4,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make unbelievable fish soup`,
    tweetImages: [
      '/images/twitter01.png',
      '/images/twitter02.png',
      '/images/twitter03.png',
      '/images/twitter04.png',
    ],
  },
  {
    no: 5,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make original fish meal`,
    tweetImages: ['/images/twitter01.png'],
  },
  {
    no: 6,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make fish`,
    tweetImages: ['/images/twitter01.png', '/images/twitter02.png'],
  },
  {
    no: 7,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can not make meat`,
    tweetImages: ['/images/twitter01.png', '/images/twitter02.png', '/images/twitter03.png'],
  },
  {
    no: 8,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make fish tower`,
    tweetImages: [],
  },
  {
    no: 9,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make super fish`,
    tweetImages: [
      '/images/twitter01.png',
      '/images/twitter02.png',
      '/images/twitter03.png',
      '/images/twitter04.png',
    ],
  },
  {
    no: 10,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make fish and chips`,
    tweetImages: ['/images/twitter02.png', '/images/twitter03.png', '/images/twitter04.png'],
  },
  {
    no: 11,
    url: 'https://twitter.com/nyaomaru',
    logo: '/images/twitter.svg',
    userIcon: '/images/client-img.png',
    tweet: `I can make all fish`,
    tweetImages: ['/images/twitter01.png', '/images/twitter02.png', '/images/twitter04.png'],
  },
];
